### ISSUE TITLE
[TASK] Update microQR generator plugin to work with KiCad 7.0

### ISSUE THREAD

**Issue by amberstarlight** [Cutie-Club/kicad-plugins#14]
As per title. I'll update this issue with a trace shortly.

**Comment by amberstarlight** [comment]
```
Traceback (most recent call last):

  File "/usr/lib/python3.10/site-packages/pcbnew.py", line 4917, in GetFootprint
    self.BuildFootprint()

  File "/usr/share/kicad/scripting/plugins/FootprintWizardBase.py", line 154, in BuildFootprint
    self.BuildThisFootprint()  # implementer's build function

  File "/usr/share/kicad/scripting/plugins/qrcode_footprint_wizard_segno.py", line 194, in BuildThisFootprint
    self.__add_mask_cutout()

  File "/usr/share/kicad/scripting/plugins/qrcode_footprint_wizard_segno.py", line 138, in __add_mask_cutout
    pad.SetSize(pcbnew.wxSize(

  File "/usr/lib/python3.10/site-packages/pcbnew.py", line 12617, in SetSize
    return _pcbnew.PAD_SetSize(self, aSize)

TypeError: in method 'PAD_SetSize', argument 2 of type 'VECTOR2I const &'


```
